server:
  port: 80
spring:
  application:
    name: order-consuer

eureka:
  client:

    fetch-registry: true
    #将自己注册
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka